import os
from dotenv import load_dotenv

load_dotenv()

OUTPUT_DIRECTORY = os.path.join(os.getcwd(), "../out")

ETHERSCAN_API_KEY = os.getenv("ETHERSCAN_API_KEY")
ALCHEMY_API_KEY = os.getenv("ALCHEMY_API_KEY")
BINANCE_API_KEY = os.getenv("BINANCE_API_KEY")
BINANCE_API_SECRET = os.getenv("BINANCE_API_SECRET")
ALCHEMY_UNICHAIN_BASE_RPC_URL = os.getenv("ALCHEMY_UNICHAIN_BASE_RPC_URL")

# Mainnet
CHAINID_MAINNET = os.getenv("CHAINID_MAINNET")
MAINNET_UNISWAP_V2_ROUTER_02 = os.getenv("MAINNET_UNISWAP_V2_ROUTER_02")
MAINNET_SUSHISWAP_ROUTER_ADDRESS = os.getenv("MAINNET_SUSHISWAP_ROUTER_ADDRESS")

# Unichain
CHAINID_UNICHAIN = os.getenv("CHAINID_UNICHAIN")
UNICHAIN_UNIVERSAL_ROUTER_V2_ADDRESS = os.getenv("UNICHAIN_UNIVERSAL_ROUTER_V2_ADDRESS")
UNICHAIN_UNISWAP_V2_ROUTER_02 = os.getenv("UNICHAIN_UNISWAP_V2_ROUTER_02")
UNICHAIN_UNISWAP_V2_FACTORY = os.getenv("UNICHAIN_UNISWAP_V2_FACTORY")
UNICHAIN_WETH = os.getenv("UNICHAIN_WETH")
UNICHAIN_USDC = os.getenv("UNICHAIN_USDC")
